export let all_info = {1001: {id: "1001",
                              name: "Dorival Júnior",
                              position: "C",
                              nationality: "BRA",
                              },
                       2001: {id: "2001",
                              name: "Santos",
                              position: "G",
                              nationality: "BRA",
                              },
                       2002: {id: "2002",
                              name: "Jandrei",
                              position: "G",
                              nationality: "BRA",
                              },
                       2003: {id: "2003",
                              name: "Léo Vieira",
                              position: "G",
                              nationality: "BRA",
                              },
                       2004: {id: "2004",
                              name: "Lucas Halter",
                              position: "D",
                              nationality: "BRA",
                              },
                       2005: {id: "2005",
                              name: "Felipe Aguilar",
                              position: "D",
                              nationality: "COL",
                              },
                       2006: {id: "2006",
                              name: "Thiago Heleno",
                              position: "D",
                              nationality: "BRA",
                              },
                       2007: {id: "2007",
                              name: "Robson Bambu",
                              position: "D",
                              nationality: "BRA",
                              },
                       2008: {id: "2008",
                              name: "Zé Ivaldo",
                              position: "D",
                              nationality: "BRA",
                              },
                       2009: {id: "2009",
                              name: "Abner",
                              position: "D",
                              nationality: "BRA",
                              },
                       2010: {id: "2010",
                              name: "Márcio Azevedo",
                              position: "D",
                              nationality: "BRA",
                              },
                       2011: {id: "2011",
                              name: "Adriano",
                              position: "D",
                              nationality: "BRA",
                              },
                       2012: {id: "2012",
                              name: "Jonathan",
                              position: "D",
                              nationality: "BRA",
                              },
                       2013: {id: "2013",
                              name: "Wellington",
                              position: "M",
                              nationality: "BRA",
                              },
                       2014: {id: "2014",
                              name: "Léo Cittadini",
                              position: "M",
                              nationality: "BRA",
                              },
                       2015: {id: "2015",
                              name: "Erick",
                              position: "M",
                              nationality: "BRA",
                              },
                       2016: {id: "2016",
                              name: "Lucho González",
                              position: "M",
                              nationality: "ARG",
                              },
                       2017: {id: "2017",
                              name: "Christian",
                              position: "M",
                              nationality: "BRA",
                              },
                       2018: {id: "2018",
                              name: "Vitinho",
                              position: "M",
                              nationality: "BRA",
                              },
                       2019: {id: "2019",
                              name: "Nikão",
                              position: "M",
                              nationality: "BRA",
                              },
                       2020: {id: "2020",
                              name: "Fernando Canesin",
                              position: "M",
                              nationality: "BRA",
                              },
                       2021: {id: "2021",
                              name: "Juan Manuel Boselli",
                              position: "M",
                              nationality: "URU",
                              },
                       2022: {id: "2022",
                              name: "Marquinhos Gabriel",
                              position: "F",
                              nationality: "BRA",
                              },
                       2023: {id: "2023",
                              name: "Pedrinho",
                              position: "F",
                              nationality: "BRA",
                              },
                       2024: {id: "2024",
                              name: "Jajá",
                              position: "F",
                              nationality: "BRA",
                              },
                       2025: {id: "2025",
                              name: "Carlos Eduardo",
                              position: "F",
                              nationality: "BRA",
                              },
                       2026: {id: "2026",
                              name: "Guilherme Bissoli",
                              position: "F",
                              nationality: "BRA",
                              },
                       1: {fullName: "Club Athletico Paranaense",
                           name: "Athletico-PR",
                           nationality: "BRA",
                           id: "1",
                           coach: "1001",
                           color1: "#C8102E",
                           color2: "#2C2825",
                           strength: "561",
                           players: "[2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]",
                           },
}