
export const cruzeiro = {
  id: "cruzeiro1921",
  name: "Cruzeiro",
  fullName: "Cruzeiro Esporte Clube",
  nationality: 'BRA',
  coachId: 'marcOliv',
  cash: 27000000,
  color1: "blue",
  color2: "white",
  division: 1,
  players: [{id: '2100', name: "Fábio", power: 50, position: "G", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false}, 
            {id: '2101', name: "Rafael", power: 37, position: "G", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2102', name: "Ceará", power: 35, position: "D", starting: 0, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2103', name: "Dedé", power: 47, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2104', name: "Egídio", power: 40, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2105', name: "Léo", power: 41, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2106', name: "Manoel", power: 38, position: "D", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2107', name: "Mayke", power: 41, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2108', name: "Éverton Ribeiro", power: 50, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2109', name: "Henrique", power: 40, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2110', name: "Lucas Silva", power: 41, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2111', name: "Nilton", power: 37, position: "M", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2112', name: "Luan", power: 37, position: "A", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2113', name: "Marcelo Moreno", power: 43, position: "A", starting: 1, nationality: 'BOL', salary: 55000, salaryRenewed: false},
            {id: '2114', name: "Marquinhos", power: 38, position: "A", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2115', name: "Ricardo Goulart", power: 49, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '2116', name: "Willian", power: 42, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false}]
}

export const atleticoMG = {
  id: "atletico1906",
  name: "Atlético-MG",
  fullName: "Clube Atlético Mineiro",
  nationalty: 'BRA',
  coachId: 'cuca',
  cash: 27000000,
  color1: "black",
  color2: "white",
  division: 1,
  players: [{id: '0800', name: "Victor", power: 50, position: "G", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false}, 
            {id: '0801', name: "Giovanni", power: 34, position: "G", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0802', name: "Júnior César", power: 39, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0803', name: "Leonardo Silva", power: 43, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0804', name: "Marcos Rocha", power: 43, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0805', name: "Rafael Marques", power: 38, position: "D", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0806', name: "Réver", power: 45, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0807', name: "Josué", power: 37, position: "M", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0808', name: "Leandro Donizete", power: 40, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0809', name: "Pierre", power: 40, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0810', name: "Richarlyson", power: 36, position: "M", starting: 0, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0811', name: "Ronaldinho Gaúcho", power: 50, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0812', name: "Alecsandro", power: 37, position: "A", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0813', name: "Bernard", power: 45, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0814', name: "Diego Tardelli", power: 47, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0815', name: "Jô", power: 44, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '0816', name: "Luan", power: 43, position: "A", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false}]
}

export const flamengo = {
  id: "flamengo1895",
  name: "Flamengo",
  fullName: "Clube de Regatas Flamengo",
  nationalty: 'BRA',
  coachId: 'jorgeJesus',
  cash: 27000000,
  color1: "red",
  color2: "black",
  division: 1,
  players: [{id: '9500', name: "César", power: 34, position: "G", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false}, 
            {id: '9501', name: "Diego Alves", power: 47, position: "G", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9502', name: "Filipe Luís", power: 44, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9503', name: "Gustavo Henrique", power: 43, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9504', name: "Léo Pereira", power: 39, position: "D", starting: 0, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9505', name: "Rafinha", power: 44, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9506', name: "Renê", power: 39, position: "D", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9507', name: "Rodrigo Caio", power: 44, position: "D", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9508', name: "Éverton Ribeiro", power: 48, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9509', name: "Gérson", power: 44, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9510', name: "Giorgian De Arrascaeta", power: 45, position: "M", starting: 1, nationality: 'URU', salary: 55000, salaryRenewed: false},
            {id: '9511', name: "Thiago Maia", power: 41, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9512', name: "Willian Arão", power: 37, position: "M", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9513', name: "Bruno Henrique", power: 49, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9514', name: "Gabigol", power: 50, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9515', name: "Michael", power: 42, position: "A", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9516', name: "Pedro", power: 42, position: "A", starting: 2, nationality: 'BRA', salary: 55000, salaryRenewed: false}]
}

export const liverpool = {
  id: "liverpool1892",
  name: "Liverpool",
  fullName: "Liverpool Football Club",
  nationalty: 'ENG',
  coachId: 'jurgKlopp',
  cash: 120000000,
  color1: "red",
  color2: "white",
  division: 1,
  players: [{id: '9200', name: "Adrián", power: 34, position: "G", starting: 2, nationality: 'SPA', salary: 55000, salaryRenewed: false}, 
            {id: '9201', name: "Alisson", power: 50, position: "G", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9202', name: "Andrew Robertson", power: 45, position: "D", starting: 1, nationality: 'SCO', salary: 55000, salaryRenewed: false},
            {id: '9203', name: "Dejan Lovren", power: 39, position: "D", starting: 2, nationality: 'CRO', salary: 55000, salaryRenewed: false},
            {id: '9204', name: "Joe Gomez", power: 42, position: "D", starting: 1, nationality: 'ENG', salary: 55000, salaryRenewed: false},
            {id: '9205', name: "Trent Alexander-Arnold", power: 47, position: "D", starting: 1, nationality: 'ENG', salary: 55000, salaryRenewed: false},
            {id: '9206', name: "Virgil Van Dijk", power: 50, position: "D", starting: 1, nationality: 'NED', salary: 55000, salaryRenewed: false},
            {id: '9207', name: "Alex-Oxlade Chamberlain", power: 40, position: "M", starting: 2, nationality: 'ENG', salary: 55000, salaryRenewed: false},
            {id: '9208', name: "Fabinho", power: 42, position: "M", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9209', name: "James Milner", power: 40, position: "M", starting: 0, nationality: 'ENG', salary: 55000, salaryRenewed: false},
            {id: '9210', name: "Jordan Henderson", power: 43, position: "M", starting: 1, nationality: 'ENG', salary: 55000, salaryRenewed: false},
            {id: '9211', name: "Naby Keita", power: 42, position: "M", starting: 2, nationality: 'GUI', salary: 55000, salaryRenewed: false},
            {id: '9212', name: "Georginio Wijnaldum", power: 43, position: "M", starting: 1, nationality: 'NED', salary: 55000, salaryRenewed: false},
            {id: '9213', name: "Divock Origi", power: 41, position: "A", starting: 2, nationality: 'BEL', salary: 55000, salaryRenewed: false},
            {id: '9214', name: "Mohamed Salah", power: 49, position: "A", starting: 1, nationality: 'EGY', salary: 55000, salaryRenewed: false},
            {id: '9215', name: "Roberto Firmino", power: 45, position: "A", starting: 1, nationality: 'BRA', salary: 55000, salaryRenewed: false},
            {id: '9216', name: "Sadio Mané", power: 49, position: "A", starting: 1, nationality: 'SEN', salary: 55000, salaryRenewed: false}]
}
